//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCodetrace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agregation
    {
        public int Id { get; set; }
        public string CodeContenu { get; set; }
        public Nullable<int> CodeId { get; set; }
    
        public virtual Code Code { get; set; }
    }
}
