//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCodetrace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cave
    {
        public Cave()
        {
            this.Rengements = new HashSet<Rengement>();
        }
    
        public string Proprietaire { get; set; }
        public int Id { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual ICollection<Rengement> Rengements { get; set; }
    }
}
