//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCodetrace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public Code()
        {
            this.Agregations = new HashSet<Agregation>();
        }
    
        public int Id { get; set; }
        public string CodeTrace { get; set; }
    
        public virtual ICollection<Agregation> Agregations { get; set; }
        public virtual Bouteille Bouteille { get; set; }
        public virtual Cave Cave { get; set; }
        public virtual Rengement Rengement { get; set; }
    }
}
