//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCodetrace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodeTraceEntities : DbContext
    {
        public CodeTraceEntities()
            : base("name=CodeTraceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agregation> Agregations { get; set; }
        public DbSet<Bouteille> Bouteilles { get; set; }
        public DbSet<Cave> Caves { get; set; }
        public DbSet<Code> Codes { get; set; }
        public DbSet<Rengement> Rengements { get; set; }
    }
}
