//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCodetrace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rengement
    {
        public Rengement()
        {
            this.Bouteilles = new HashSet<Bouteille>();
        }
    
        public string Emplacement { get; set; }
        public string QuantiteMax { get; set; }
        public string Quantite { get; set; }
        public Nullable<int> CaveId { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Bouteille> Bouteilles { get; set; }
        public virtual Cave Cave { get; set; }
        public virtual Code Code { get; set; }
    }
}
